// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alert_log.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createAlertLogEntry = `-- name: CreateAlertLogEntry :exec
INSERT INTO alert_log (
    id, destination_id, workspace_id, drift_check_id, event_type,
    success, http_status, response_snippet, attempted_at, retry_count
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAlertLogEntryParams struct {
	ID              string         `db:"id" json:"id"`
	DestinationID   string         `db:"destination_id" json:"destination_id"`
	WorkspaceID     string         `db:"workspace_id" json:"workspace_id"`
	DriftCheckID    sql.NullString `db:"drift_check_id" json:"drift_check_id"`
	EventType       string         `db:"event_type" json:"event_type"`
	Success         bool           `db:"success" json:"success"`
	HttpStatus      sql.NullInt64  `db:"http_status" json:"http_status"`
	ResponseSnippet sql.NullString `db:"response_snippet" json:"response_snippet"`
	AttemptedAt     time.Time      `db:"attempted_at" json:"attempted_at"`
	RetryCount      int64          `db:"retry_count" json:"retry_count"`
}

func (q *Queries) CreateAlertLogEntry(ctx context.Context, arg CreateAlertLogEntryParams) error {
	_, err := q.db.ExecContext(ctx, createAlertLogEntry,
		arg.ID,
		arg.DestinationID,
		arg.WorkspaceID,
		arg.DriftCheckID,
		arg.EventType,
		arg.Success,
		arg.HttpStatus,
		arg.ResponseSnippet,
		arg.AttemptedAt,
		arg.RetryCount,
	)
	return err
}

const listAlertLogForWorkspace = `-- name: ListAlertLogForWorkspace :many
SELECT id, destination_id, workspace_id, drift_check_id, event_type, success, http_status, response_snippet, attempted_at, retry_count FROM alert_log WHERE workspace_id = ? ORDER BY attempted_at DESC LIMIT ?
`

type ListAlertLogForWorkspaceParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspace_id"`
	Limit       int64  `db:"limit" json:"limit"`
}

func (q *Queries) ListAlertLogForWorkspace(ctx context.Context, arg ListAlertLogForWorkspaceParams) ([]AlertLog, error) {
	rows, err := q.db.QueryContext(ctx, listAlertLogForWorkspace, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertLog
	for rows.Next() {
		var i AlertLog
		if err := rows.Scan(
			&i.ID,
			&i.DestinationID,
			&i.WorkspaceID,
			&i.DriftCheckID,
			&i.EventType,
			&i.Success,
			&i.HttpStatus,
			&i.ResponseSnippet,
			&i.AttemptedAt,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
