// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alert_destinations.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createAlertDestination = `-- name: CreateAlertDestination :one
INSERT INTO alert_destinations (
    id, workspace_id, name, kind, url, shared_secret, is_enabled, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, workspace_id, name, kind, url, shared_secret, is_enabled, created_at
`

type CreateAlertDestinationParams struct {
	ID           string         `db:"id" json:"id"`
	WorkspaceID  sql.NullString `db:"workspace_id" json:"workspace_id"`
	Name         string         `db:"name" json:"name"`
	Kind         string         `db:"kind" json:"kind"`
	Url          string         `db:"url" json:"url"`
	SharedSecret sql.NullString `db:"shared_secret" json:"shared_secret"`
	IsEnabled    bool           `db:"is_enabled" json:"is_enabled"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateAlertDestination(ctx context.Context, arg CreateAlertDestinationParams) (AlertDestination, error) {
	row := q.db.QueryRowContext(ctx, createAlertDestination,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Kind,
		arg.Url,
		arg.SharedSecret,
		arg.IsEnabled,
		arg.CreatedAt,
	)
	var i AlertDestination
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Kind,
		&i.Url,
		&i.SharedSecret,
		&i.IsEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAlertDestination = `-- name: DeleteAlertDestination :exec
DELETE FROM alert_destinations WHERE id = ?
`

func (q *Queries) DeleteAlertDestination(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAlertDestination, id)
	return err
}

const getAlertDestination = `-- name: GetAlertDestination :one
SELECT id, workspace_id, name, kind, url, shared_secret, is_enabled, created_at FROM alert_destinations WHERE id = ?
`

func (q *Queries) GetAlertDestination(ctx context.Context, id string) (AlertDestination, error) {
	row := q.db.QueryRowContext(ctx, getAlertDestination, id)
	var i AlertDestination
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Kind,
		&i.Url,
		&i.SharedSecret,
		&i.IsEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const listAlertDestinations = `-- name: ListAlertDestinations :many
SELECT id, workspace_id, name, kind, url, shared_secret, is_enabled, created_at FROM alert_destinations ORDER BY created_at ASC
`

func (q *Queries) ListAlertDestinations(ctx context.Context) ([]AlertDestination, error) {
	rows, err := q.db.QueryContext(ctx, listAlertDestinations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertDestination
	for rows.Next() {
		var i AlertDestination
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Kind,
			&i.Url,
			&i.SharedSecret,
			&i.IsEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertDestinationsForWorkspace = `-- name: ListAlertDestinationsForWorkspace :many
SELECT id, workspace_id, name, kind, url, shared_secret, is_enabled, created_at FROM alert_destinations
WHERE is_enabled = 1 AND (workspace_id = ? OR workspace_id IS NULL)
`

func (q *Queries) ListAlertDestinationsForWorkspace(ctx context.Context, workspaceID sql.NullString) ([]AlertDestination, error) {
	rows, err := q.db.QueryContext(ctx, listAlertDestinationsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertDestination
	for rows.Next() {
		var i AlertDestination
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Kind,
			&i.Url,
			&i.SharedSecret,
			&i.IsEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertDestination = `-- name: UpdateAlertDestination :one
UPDATE alert_destinations
SET
    workspace_id = ?,
    name = ?,
    kind = ?,
    url = ?,
    shared_secret = ?,
    is_enabled = ?
WHERE id = ?
RETURNING id, workspace_id, name, kind, url, shared_secret, is_enabled, created_at
`

type UpdateAlertDestinationParams struct {
	WorkspaceID  sql.NullString `db:"workspace_id" json:"workspace_id"`
	Name         string         `db:"name" json:"name"`
	Kind         string         `db:"kind" json:"kind"`
	Url          string         `db:"url" json:"url"`
	SharedSecret sql.NullString `db:"shared_secret" json:"shared_secret"`
	IsEnabled    bool           `db:"is_enabled" json:"is_enabled"`
	ID           string         `db:"id" json:"id"`
}

func (q *Queries) UpdateAlertDestination(ctx context.Context, arg UpdateAlertDestinationParams) (AlertDestination, error) {
	row := q.db.QueryRowContext(ctx, updateAlertDestination,
		arg.WorkspaceID,
		arg.Name,
		arg.Kind,
		arg.Url,
		arg.SharedSecret,
		arg.IsEnabled,
		arg.ID,
	)
	var i AlertDestination
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Kind,
		&i.Url,
		&i.SharedSecret,
		&i.IsEnabled,
		&i.CreatedAt,
	)
	return i, err
}
