// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (id, user_id, name, token_hash, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, name, token_hash, created_at, last_used_at, revoked_at
`

type CreateAPITokenParams struct {
	ID        string    `db:"id" json:"id"`
	UserID    string    `db:"user_id" json:"user_id"`
	Name      string    `db:"name" json:"name"`
	TokenHash string    `db:"token_hash" json:"token_hash"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, createAPIToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveAPITokenByHash = `-- name: GetActiveAPITokenByHash :one
SELECT id, user_id, name, token_hash, created_at, last_used_at, revoked_at FROM api_tokens WHERE token_hash = ? AND revoked_at IS NULL
`

func (q *Queries) GetActiveAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getActiveAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPITokensForUser = `-- name: ListAPITokensForUser :many
SELECT id, user_id, name, token_hash, created_at, last_used_at, revoked_at FROM api_tokens WHERE user_id = ? AND revoked_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListAPITokensForUser(ctx context.Context, userID string) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec
UPDATE api_tokens SET revoked_at = ? WHERE id = ? AND user_id = ?
`

type RevokeAPITokenParams struct {
	RevokedAt sql.NullTime `db:"revoked_at" json:"revoked_at"`
	ID        string       `db:"id" json:"id"`
	UserID    string       `db:"user_id" json:"user_id"`
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeAPIToken, arg.RevokedAt, arg.ID, arg.UserID)
	return err
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = ? WHERE id = ?
`

type TouchAPITokenParams struct {
	LastUsedAt sql.NullTime `db:"last_used_at" json:"last_used_at"`
	ID         string       `db:"id" json:"id"`
}

func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, touchAPIToken, arg.LastUsedAt, arg.ID)
	return err
}
