// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drift_resources.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createDriftResource = `-- name: CreateDriftResource :exec
INSERT INTO drift_resources (
    id, drift_check_id, resource_address, resource_type, module_address,
    action, before_json, after_json, has_sensitive, has_unknown
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDriftResourceParams struct {
	ID              string         `db:"id" json:"id"`
	DriftCheckID    string         `db:"drift_check_id" json:"drift_check_id"`
	ResourceAddress string         `db:"resource_address" json:"resource_address"`
	ResourceType    string         `db:"resource_type" json:"resource_type"`
	ModuleAddress   sql.NullString `db:"module_address" json:"module_address"`
	Action          string         `db:"action" json:"action"`
	BeforeJson      sql.NullString `db:"before_json" json:"before_json"`
	AfterJson       sql.NullString `db:"after_json" json:"after_json"`
	HasSensitive    bool           `db:"has_sensitive" json:"has_sensitive"`
	HasUnknown      bool           `db:"has_unknown" json:"has_unknown"`
}

func (q *Queries) CreateDriftResource(ctx context.Context, arg CreateDriftResourceParams) error {
	_, err := q.db.ExecContext(ctx, createDriftResource,
		arg.ID,
		arg.DriftCheckID,
		arg.ResourceAddress,
		arg.ResourceType,
		arg.ModuleAddress,
		arg.Action,
		arg.BeforeJson,
		arg.AfterJson,
		arg.HasSensitive,
		arg.HasUnknown,
	)
	return err
}

const listDriftResourcesForCheck = `-- name: ListDriftResourcesForCheck :many
SELECT id, drift_check_id, resource_address, resource_type, module_address, "action", before_json, after_json, has_sensitive, has_unknown FROM drift_resources WHERE drift_check_id = ? ORDER BY resource_address ASC
`

func (q *Queries) ListDriftResourcesForCheck(ctx context.Context, driftCheckID string) ([]DriftResource, error) {
	rows, err := q.db.QueryContext(ctx, listDriftResourcesForCheck, driftCheckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriftResource
	for rows.Next() {
		var i DriftResource
		if err := rows.Scan(
			&i.ID,
			&i.DriftCheckID,
			&i.ResourceAddress,
			&i.ResourceType,
			&i.ModuleAddress,
			&i.Action,
			&i.BeforeJson,
			&i.AfterJson,
			&i.HasSensitive,
			&i.HasUnknown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
