// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drift_checks.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createDriftCheck = `-- name: CreateDriftCheck :one
INSERT INTO drift_checks (
    id, workspace_id, status, started_at, finished_at, duration_ms,
    resources_added, resources_changed, resources_destroyed, resources_unchanged,
    error_message, triggered_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, workspace_id, status, started_at, finished_at, duration_ms, resources_added, resources_changed, resources_destroyed, resources_unchanged, error_message, triggered_by
`

type CreateDriftCheckParams struct {
	ID                 string         `db:"id" json:"id"`
	WorkspaceID        string         `db:"workspace_id" json:"workspace_id"`
	Status             string         `db:"status" json:"status"`
	StartedAt          time.Time      `db:"started_at" json:"started_at"`
	FinishedAt         sql.NullTime   `db:"finished_at" json:"finished_at"`
	DurationMs         sql.NullInt64  `db:"duration_ms" json:"duration_ms"`
	ResourcesAdded     int64          `db:"resources_added" json:"resources_added"`
	ResourcesChanged   int64          `db:"resources_changed" json:"resources_changed"`
	ResourcesDestroyed int64          `db:"resources_destroyed" json:"resources_destroyed"`
	ResourcesUnchanged int64          `db:"resources_unchanged" json:"resources_unchanged"`
	ErrorMessage       sql.NullString `db:"error_message" json:"error_message"`
	TriggeredBy        string         `db:"triggered_by" json:"triggered_by"`
}

func (q *Queries) CreateDriftCheck(ctx context.Context, arg CreateDriftCheckParams) (DriftCheck, error) {
	row := q.db.QueryRowContext(ctx, createDriftCheck,
		arg.ID,
		arg.WorkspaceID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
		arg.ResourcesAdded,
		arg.ResourcesChanged,
		arg.ResourcesDestroyed,
		arg.ResourcesUnchanged,
		arg.ErrorMessage,
		arg.TriggeredBy,
	)
	var i DriftCheck
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ResourcesAdded,
		&i.ResourcesChanged,
		&i.ResourcesDestroyed,
		&i.ResourcesUnchanged,
		&i.ErrorMessage,
		&i.TriggeredBy,
	)
	return i, err
}

const getDriftCheck = `-- name: GetDriftCheck :one
SELECT id, workspace_id, status, started_at, finished_at, duration_ms, resources_added, resources_changed, resources_destroyed, resources_unchanged, error_message, triggered_by FROM drift_checks WHERE id = ?
`

func (q *Queries) GetDriftCheck(ctx context.Context, id string) (DriftCheck, error) {
	row := q.db.QueryRowContext(ctx, getDriftCheck, id)
	var i DriftCheck
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ResourcesAdded,
		&i.ResourcesChanged,
		&i.ResourcesDestroyed,
		&i.ResourcesUnchanged,
		&i.ErrorMessage,
		&i.TriggeredBy,
	)
	return i, err
}

const listDriftChecksForWorkspace = `-- name: ListDriftChecksForWorkspace :many
SELECT id, workspace_id, status, started_at, finished_at, duration_ms, resources_added, resources_changed, resources_destroyed, resources_unchanged, error_message, triggered_by FROM drift_checks WHERE workspace_id = ? ORDER BY started_at DESC LIMIT ?
`

type ListDriftChecksForWorkspaceParams struct {
	WorkspaceID string `db:"workspace_id" json:"workspace_id"`
	Limit       int64  `db:"limit" json:"limit"`
}

func (q *Queries) ListDriftChecksForWorkspace(ctx context.Context, arg ListDriftChecksForWorkspaceParams) ([]DriftCheck, error) {
	rows, err := q.db.QueryContext(ctx, listDriftChecksForWorkspace, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriftCheck
	for rows.Next() {
		var i DriftCheck
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ResourcesAdded,
			&i.ResourcesChanged,
			&i.ResourcesDestroyed,
			&i.ResourcesUnchanged,
			&i.ErrorMessage,
			&i.TriggeredBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
