// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type DriftCheck struct {
	ID                 string         `db:"id" json:"id"`
	WorkspaceID        string         `db:"workspace_id" json:"workspace_id"`
	Status             string         `db:"status" json:"status"`
	StartedAt          time.Time      `db:"started_at" json:"started_at"`
	FinishedAt         sql.NullTime   `db:"finished_at" json:"finished_at"`
	DurationMs         sql.NullInt64  `db:"duration_ms" json:"duration_ms"`
	ResourcesAdded     int64          `db:"resources_added" json:"resources_added"`
	ResourcesChanged   int64          `db:"resources_changed" json:"resources_changed"`
	ResourcesDestroyed int64          `db:"resources_destroyed" json:"resources_destroyed"`
	ResourcesUnchanged int64          `db:"resources_unchanged" json:"resources_unchanged"`
	ErrorMessage       sql.NullString `db:"error_message" json:"error_message"`
	TriggeredBy        string         `db:"triggered_by" json:"triggered_by"`
}

type DriftResource struct {
	ID              string         `db:"id" json:"id"`
	DriftCheckID    string         `db:"drift_check_id" json:"drift_check_id"`
	ResourceAddress string         `db:"resource_address" json:"resource_address"`
	ResourceType    string         `db:"resource_type" json:"resource_type"`
	ModuleAddress   sql.NullString `db:"module_address" json:"module_address"`
	Action          string         `db:"action" json:"action"`
	BeforeJson      sql.NullString `db:"before_json" json:"before_json"`
	AfterJson       sql.NullString `db:"after_json" json:"after_json"`
	HasSensitive    bool           `db:"has_sensitive" json:"has_sensitive"`
	HasUnknown      bool           `db:"has_unknown" json:"has_unknown"`
}

type Session struct {
	TokenHash  string         `db:"token_hash" json:"token_hash"`
	UserID     string         `db:"user_id" json:"user_id"`
	CreatedAt  time.Time      `db:"created_at" json:"created_at"`
	ExpiresAt  time.Time      `db:"expires_at" json:"expires_at"`
	LastSeenAt time.Time      `db:"last_seen_at" json:"last_seen_at"`
	IpAddress  sql.NullString `db:"ip_address" json:"ip_address"`
	UserAgent  sql.NullString `db:"user_agent" json:"user_agent"`
}

type User struct {
	ID           string       `db:"id" json:"id"`
	Email        string       `db:"email" json:"email"`
	PasswordHash string       `db:"password_hash" json:"password_hash"`
	CreatedAt    time.Time    `db:"created_at" json:"created_at"`
	LastLoginAt  sql.NullTime `db:"last_login_at" json:"last_login_at"`
}

type Workspace struct {
	ID                   string         `db:"id" json:"id"`
	Name                 string         `db:"name" json:"name"`
	Description          sql.NullString `db:"description" json:"description"`
	SourcePath           string         `db:"source_path" json:"source_path"`
	WorkingSubdirectory  sql.NullString `db:"working_subdirectory" json:"working_subdirectory"`
	BinaryKind           string         `db:"binary_kind" json:"binary_kind"`
	BinaryVersion        sql.NullString `db:"binary_version" json:"binary_version"`
	CredentialEnvFile    sql.NullString `db:"credential_env_file" json:"credential_env_file"`
	CheckIntervalMinutes int64          `db:"check_interval_minutes" json:"check_interval_minutes"`
	CheckTimeoutSeconds  int64          `db:"check_timeout_seconds" json:"check_timeout_seconds"`
	IsEnabled            bool           `db:"is_enabled" json:"is_enabled"`
	LastCheckID          sql.NullString `db:"last_check_id" json:"last_check_id"`
	LastCheckStatus      sql.NullString `db:"last_check_status" json:"last_check_status"`
	CreatedBy            sql.NullString `db:"created_by" json:"created_by"`
	CreatedAt            time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt            time.Time      `db:"updated_at" json:"updated_at"`
}
