// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type Session struct {
	TokenHash  string         `db:"token_hash" json:"token_hash"`
	UserID     string         `db:"user_id" json:"user_id"`
	CreatedAt  time.Time      `db:"created_at" json:"created_at"`
	ExpiresAt  time.Time      `db:"expires_at" json:"expires_at"`
	LastSeenAt time.Time      `db:"last_seen_at" json:"last_seen_at"`
	IpAddress  sql.NullString `db:"ip_address" json:"ip_address"`
	UserAgent  sql.NullString `db:"user_agent" json:"user_agent"`
}

type User struct {
	ID           string       `db:"id" json:"id"`
	Email        string       `db:"email" json:"email"`
	PasswordHash string       `db:"password_hash" json:"password_hash"`
	CreatedAt    time.Time    `db:"created_at" json:"created_at"`
	LastLoginAt  sql.NullTime `db:"last_login_at" json:"last_login_at"`
}
