// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"time"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateDriftCheck(ctx context.Context, arg CreateDriftCheckParams) (DriftCheck, error)
	CreateDriftResource(ctx context.Context, arg CreateDriftResourceParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error
	DeleteSession(ctx context.Context, tokenHash string) error
	DeleteSessionsForUser(ctx context.Context, userID string) error
	DeleteWorkspace(ctx context.Context, id string) error
	GetDriftCheck(ctx context.Context, id string) (DriftCheck, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetWorkspace(ctx context.Context, id string) (Workspace, error)
	GetWorkspaceByName(ctx context.Context, name string) (Workspace, error)
	ListDriftChecksForWorkspace(ctx context.Context, arg ListDriftChecksForWorkspaceParams) ([]DriftCheck, error)
	ListDriftResourcesForCheck(ctx context.Context, driftCheckID string) ([]DriftResource, error)
	// Deliberately does no date arithmetic here: it just joins each enabled
	// workspace to its last check's started_at (NULL if it's never been
	// checked) and leaves "is it actually due yet" - comparing that against
	// the workspace's own check_interval_minutes - to the scheduler, in Go,
	// where it's easy to test with a fake clock instead of relying on
	// SQLite's dynamic-interval date functions.
	ListEnabledWorkspacesWithLastCheck(ctx context.Context) ([]ListEnabledWorkspacesWithLastCheckRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListWorkspaces(ctx context.Context) ([]Workspace, error)
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	UpdateWorkspaceLastCheck(ctx context.Context, arg UpdateWorkspaceLastCheckParams) error
}

var _ Querier = (*Queries)(nil)
