// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, created_at, expires_at, last_seen_at, ip_address, user_agent)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	TokenHash  string         `db:"token_hash" json:"token_hash"`
	UserID     string         `db:"user_id" json:"user_id"`
	CreatedAt  time.Time      `db:"created_at" json:"created_at"`
	ExpiresAt  time.Time      `db:"expires_at" json:"expires_at"`
	LastSeenAt time.Time      `db:"last_seen_at" json:"last_seen_at"`
	IpAddress  sql.NullString `db:"ip_address" json:"ip_address"`
	UserAgent  sql.NullString `db:"user_agent" json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsForUser, userID)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT token_hash, user_id, created_at, expires_at, last_seen_at, ip_address, user_agent FROM sessions WHERE token_hash = ?
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.IpAddress,
		&i.UserAgent,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = ? WHERE token_hash = ?
`

type TouchSessionParams struct {
	LastSeenAt time.Time `db:"last_seen_at" json:"last_seen_at"`
	TokenHash  string    `db:"token_hash" json:"token_hash"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastSeenAt, arg.TokenHash)
	return err
}
