// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (
    id, name, description, source_path, working_subdirectory,
    binary_kind, binary_version, credential_env_file,
    check_interval_minutes, check_timeout_seconds, is_enabled,
    created_by, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, source_path, working_subdirectory, binary_kind, binary_version, credential_env_file, check_interval_minutes, check_timeout_seconds, is_enabled, last_check_id, last_check_status, created_by, created_at, updated_at
`

type CreateWorkspaceParams struct {
	ID                   string         `db:"id" json:"id"`
	Name                 string         `db:"name" json:"name"`
	Description          sql.NullString `db:"description" json:"description"`
	SourcePath           string         `db:"source_path" json:"source_path"`
	WorkingSubdirectory  sql.NullString `db:"working_subdirectory" json:"working_subdirectory"`
	BinaryKind           string         `db:"binary_kind" json:"binary_kind"`
	BinaryVersion        sql.NullString `db:"binary_version" json:"binary_version"`
	CredentialEnvFile    sql.NullString `db:"credential_env_file" json:"credential_env_file"`
	CheckIntervalMinutes int64          `db:"check_interval_minutes" json:"check_interval_minutes"`
	CheckTimeoutSeconds  int64          `db:"check_timeout_seconds" json:"check_timeout_seconds"`
	IsEnabled            bool           `db:"is_enabled" json:"is_enabled"`
	CreatedBy            sql.NullString `db:"created_by" json:"created_by"`
	CreatedAt            time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt            time.Time      `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SourcePath,
		arg.WorkingSubdirectory,
		arg.BinaryKind,
		arg.BinaryVersion,
		arg.CredentialEnvFile,
		arg.CheckIntervalMinutes,
		arg.CheckTimeoutSeconds,
		arg.IsEnabled,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SourcePath,
		&i.WorkingSubdirectory,
		&i.BinaryKind,
		&i.BinaryVersion,
		&i.CredentialEnvFile,
		&i.CheckIntervalMinutes,
		&i.CheckTimeoutSeconds,
		&i.IsEnabled,
		&i.LastCheckID,
		&i.LastCheckStatus,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = ?
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, description, source_path, working_subdirectory, binary_kind, binary_version, credential_env_file, check_interval_minutes, check_timeout_seconds, is_enabled, last_check_id, last_check_status, created_by, created_at, updated_at FROM workspaces WHERE id = ?
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SourcePath,
		&i.WorkingSubdirectory,
		&i.BinaryKind,
		&i.BinaryVersion,
		&i.CredentialEnvFile,
		&i.CheckIntervalMinutes,
		&i.CheckTimeoutSeconds,
		&i.IsEnabled,
		&i.LastCheckID,
		&i.LastCheckStatus,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByName = `-- name: GetWorkspaceByName :one
SELECT id, name, description, source_path, working_subdirectory, binary_kind, binary_version, credential_env_file, check_interval_minutes, check_timeout_seconds, is_enabled, last_check_id, last_check_status, created_by, created_at, updated_at FROM workspaces WHERE name = ?
`

func (q *Queries) GetWorkspaceByName(ctx context.Context, name string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByName, name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SourcePath,
		&i.WorkingSubdirectory,
		&i.BinaryKind,
		&i.BinaryVersion,
		&i.CredentialEnvFile,
		&i.CheckIntervalMinutes,
		&i.CheckTimeoutSeconds,
		&i.IsEnabled,
		&i.LastCheckID,
		&i.LastCheckStatus,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, description, source_path, working_subdirectory, binary_kind, binary_version, credential_env_file, check_interval_minutes, check_timeout_seconds, is_enabled, last_check_id, last_check_status, created_by, created_at, updated_at FROM workspaces ORDER BY name ASC
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SourcePath,
			&i.WorkingSubdirectory,
			&i.BinaryKind,
			&i.BinaryVersion,
			&i.CredentialEnvFile,
			&i.CheckIntervalMinutes,
			&i.CheckTimeoutSeconds,
			&i.IsEnabled,
			&i.LastCheckID,
			&i.LastCheckStatus,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET
    name = ?,
    description = ?,
    source_path = ?,
    working_subdirectory = ?,
    binary_kind = ?,
    binary_version = ?,
    credential_env_file = ?,
    check_interval_minutes = ?,
    check_timeout_seconds = ?,
    is_enabled = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, name, description, source_path, working_subdirectory, binary_kind, binary_version, credential_env_file, check_interval_minutes, check_timeout_seconds, is_enabled, last_check_id, last_check_status, created_by, created_at, updated_at
`

type UpdateWorkspaceParams struct {
	Name                 string         `db:"name" json:"name"`
	Description          sql.NullString `db:"description" json:"description"`
	SourcePath           string         `db:"source_path" json:"source_path"`
	WorkingSubdirectory  sql.NullString `db:"working_subdirectory" json:"working_subdirectory"`
	BinaryKind           string         `db:"binary_kind" json:"binary_kind"`
	BinaryVersion        sql.NullString `db:"binary_version" json:"binary_version"`
	CredentialEnvFile    sql.NullString `db:"credential_env_file" json:"credential_env_file"`
	CheckIntervalMinutes int64          `db:"check_interval_minutes" json:"check_interval_minutes"`
	CheckTimeoutSeconds  int64          `db:"check_timeout_seconds" json:"check_timeout_seconds"`
	IsEnabled            bool           `db:"is_enabled" json:"is_enabled"`
	UpdatedAt            time.Time      `db:"updated_at" json:"updated_at"`
	ID                   string         `db:"id" json:"id"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, updateWorkspace,
		arg.Name,
		arg.Description,
		arg.SourcePath,
		arg.WorkingSubdirectory,
		arg.BinaryKind,
		arg.BinaryVersion,
		arg.CredentialEnvFile,
		arg.CheckIntervalMinutes,
		arg.CheckTimeoutSeconds,
		arg.IsEnabled,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SourcePath,
		&i.WorkingSubdirectory,
		&i.BinaryKind,
		&i.BinaryVersion,
		&i.CredentialEnvFile,
		&i.CheckIntervalMinutes,
		&i.CheckTimeoutSeconds,
		&i.IsEnabled,
		&i.LastCheckID,
		&i.LastCheckStatus,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspaceLastCheck = `-- name: UpdateWorkspaceLastCheck :exec
UPDATE workspaces SET last_check_id = ?, last_check_status = ? WHERE id = ?
`

type UpdateWorkspaceLastCheckParams struct {
	LastCheckID     sql.NullString `db:"last_check_id" json:"last_check_id"`
	LastCheckStatus sql.NullString `db:"last_check_status" json:"last_check_status"`
	ID              string         `db:"id" json:"id"`
}

func (q *Queries) UpdateWorkspaceLastCheck(ctx context.Context, arg UpdateWorkspaceLastCheckParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspaceLastCheck, arg.LastCheckID, arg.LastCheckStatus, arg.ID)
	return err
}
